# Generated by Django 6.0 on 2026-01-17 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Czlonek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=70)),
                ('e_mail', models.CharField(max_length=70, unique=True)),
                ('indeks', models.IntegerField(blank=True, null=True, unique=True)),
                ('telefon', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Członek',
                'verbose_name_plural': 'Członkowie',
                'db_table': 'czlonek',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kierunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Kierunek',
                'verbose_name_plural': 'Kierunki',
                'db_table': 'kierunek',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OdpowiedziSlownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Odpowiedź Słownik',
                'verbose_name_plural': 'Odpowiedzi Słownik',
                'db_table': 'odpowiedzi_slownik',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Organizacja',
                'verbose_name_plural': 'Organizacje',
                'db_table': 'organizacja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('numer_telefonu', models.IntegerField(blank=True, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=70, null=True)),
                ('osoba_odpowiedzialna', models.IntegerField()),
                ('przychod', models.DecimalField(decimal_places=2, max_digits=20)),
                ('odpowiedz', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partnerzy',
                'db_table': 'partner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=80)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
                'db_table': 'projekt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sekcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Sekcja',
                'verbose_name_plural': 'Sekcje',
                'db_table': 'sekcja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rola', models.TextField()),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
                'db_table': 'uzytkownik',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WidokBazyCzlonkow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('czlonek_imie', models.CharField(blank=True, max_length=50, null=True)),
                ('czlonek_nazwisko', models.CharField(blank=True, max_length=70, null=True)),
                ('czlonek_email', models.CharField(blank=True, max_length=70, null=True)),
                ('indeks', models.IntegerField(blank=True, null=True)),
                ('telefon', models.IntegerField(blank=True, null=True)),
                ('data_aktualizacji', models.DateTimeField()),
                ('kierunek_nazwa', models.CharField(blank=True, max_length=50, null=True)),
                ('projekt_nazwa', models.CharField(blank=True, max_length=80, null=True)),
                ('sekcja_nazwa', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Widok Bazy Członków',
                'verbose_name_plural': 'Widoki Bazy Członków',
                'db_table': 'widok_bazy_czlonkow',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WidokBudzetu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('przychod_kwota', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('przychod_nazwa', models.CharField(blank=True, max_length=60, null=True)),
                ('przychod_updated_at', models.DateTimeField(blank=True, null=True)),
                ('osoba_przychod_imie', models.CharField(blank=True, max_length=50, null=True)),
                ('osoba_przychod_nazwisko', models.CharField(blank=True, max_length=70, null=True)),
                ('wydatek_kwota', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('wydatek_nazwa', models.CharField(blank=True, max_length=60, null=True)),
                ('wydatek_updated_at', models.DateTimeField(blank=True, null=True)),
                ('osoba_wydatek_imie', models.CharField(blank=True, max_length=50, null=True)),
                ('osoba_wydatek_nazwisko', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'verbose_name': 'Widok Budżetu',
                'verbose_name_plural': 'Widoki Budżetu',
                'db_table': 'widok_budzetu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WidokCertyfikatow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('czlonek_imie', models.CharField(blank=True, max_length=50, null=True)),
                ('czlonek_nazwisko', models.CharField(blank=True, max_length=70, null=True)),
                ('projekt_nazwa', models.CharField(blank=True, max_length=80, null=True)),
                ('projekt_data_rozpoczecia', models.DateTimeField(blank=True, null=True)),
                ('certyfikat_data_wystawienia', models.DateTimeField(blank=True, null=True)),
                ('sekcja_nazwa', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Widok Certyfikatów',
                'verbose_name_plural': 'Widoki Certyfikatów',
                'db_table': 'widok_certyfikatow',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WidokObecnosci',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('czlonek_imie', models.CharField(blank=True, max_length=50, null=True)),
                ('czlonek_nazwisko', models.CharField(blank=True, max_length=70, null=True)),
                ('czlonek_email', models.CharField(blank=True, max_length=70, null=True)),
                ('spotkanie_data', models.DateTimeField(blank=True, null=True)),
                ('sekcja_nazwa', models.CharField(blank=True, max_length=50, null=True)),
                ('czy_obecny', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Widok Obecności',
                'verbose_name_plural': 'Widoki Obecności',
                'db_table': 'widok_obecnosci',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WidokPartnerow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('partner_nazwa', models.CharField(blank=True, max_length=100, null=True)),
                ('numer_telefonu', models.IntegerField(blank=True, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=70, null=True)),
                ('odpowiedz', models.CharField(blank=True, max_length=50, null=True)),
                ('osoba_odp_imie', models.CharField(blank=True, max_length=50, null=True)),
                ('osoba_odp_nazwisko', models.CharField(blank=True, max_length=70, null=True)),
                ('osoba_odp_e_mail', models.CharField(blank=True, max_length=70, null=True)),
                ('przychod_kwota', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'verbose_name': 'Widok Partnerów',
                'verbose_name_plural': 'Widoki Partnerów',
                'db_table': 'widok_partnerow',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Czlonekkierunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('id_czlonek', models.ForeignKey(db_column='id_czlonek', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.czlonek')),
                ('id_kierunku', models.ForeignKey(db_column='id_kierunku', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.kierunek')),
            ],
            options={
                'verbose_name': 'Członek Kierunku',
                'verbose_name_plural': 'Członkowie Kierunków',
                'db_table': 'czlonekkierunek',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Czlonekprojektu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('id_czlonek', models.ForeignKey(db_column='id_czlonek', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.czlonek')),
                ('id_projekt', models.ForeignKey(db_column='id_projekt', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.projekt')),
            ],
            options={
                'verbose_name': 'Członek Projektu',
                'verbose_name_plural': 'Członkowie Projektów',
                'db_table': 'czlonekprojektu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Przychod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nazwa', models.CharField(max_length=60)),
                ('data', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('id_partner', models.ForeignKey(blank=True, db_column='id_partner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner_przychody', to='organizacja.partner')),
                ('osoba_odpowiedzialna', models.ForeignKey(db_column='osoba_odpowiedzialna', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.czlonek')),
            ],
            options={
                'verbose_name': 'Przychód',
                'verbose_name_plural': 'Przychody',
                'db_table': 'przychod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Czloneksekcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('id_czlonek', models.ForeignKey(db_column='id_czlonek', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.czlonek')),
                ('id_sekcja', models.ForeignKey(db_column='id_sekcja', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.sekcja')),
            ],
            options={
                'verbose_name': 'Członek Sekcji',
                'verbose_name_plural': 'Członkowie Sekcji',
                'db_table': 'czloneksekcji',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Certyfikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('id_czlonka', models.ForeignKey(db_column='id_czlonka', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.czlonek')),
                ('id_projekt', models.ForeignKey(db_column='id_projekt', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.projekt')),
                ('id_sekcja', models.ForeignKey(db_column='id_sekcja', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.sekcja')),
            ],
            options={
                'verbose_name': 'Certyfikat',
                'verbose_name_plural': 'Certyfikaty',
                'db_table': 'certyfikat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Spotkanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('id_organizatora', models.ForeignKey(db_column='id_organizatora', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.czlonek')),
            ],
            options={
                'verbose_name': 'Spotkanie',
                'verbose_name_plural': 'Spotkania',
                'db_table': 'spotkanie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Spotkanieczlonek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_obecny', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('id_czlonka', models.ForeignKey(db_column='id_czlonka', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.czlonek')),
                ('id_spotkania', models.ForeignKey(db_column='id_spotkania', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.spotkanie')),
            ],
            options={
                'verbose_name': 'Spotkanie Członek',
                'verbose_name_plural': 'Spotkania Członkowie',
                'db_table': 'spotkanieczlonek',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='czlonek',
            name='id_uzytkownika',
            field=models.ForeignKey(blank=True, db_column='id_uzytkownika', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.uzytkownik'),
        ),
        migrations.CreateModel(
            name='Uzytkownikorganizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=70, unique=True)),
                ('haslo', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('id_organizacja', models.ForeignKey(db_column='id_organizacja', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.organizacja')),
                ('id_uzytkownik', models.ForeignKey(db_column='id_uzytkownik', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.uzytkownik')),
            ],
            options={
                'verbose_name': 'Użytkownik Organizacja',
                'verbose_name_plural': 'Użytkownicy Organizacje',
                'db_table': 'uzytkownikorganizacja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wydatek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nazwa', models.CharField(max_length=60)),
                ('data', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('osoba_odpowiedzialna', models.ForeignKey(db_column='osoba_odpowiedzialna', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.czlonek')),
            ],
            options={
                'verbose_name': 'Wydatek',
                'verbose_name_plural': 'Wydatki',
                'db_table': 'wydatek',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Budzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=20)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('id_przychod', models.ForeignKey(db_column='id_przychod', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.przychod')),
                ('id_wydatek', models.ForeignKey(db_column='id_wydatek', on_delete=django.db.models.deletion.DO_NOTHING, to='organizacja.wydatek')),
            ],
            options={
                'verbose_name': 'Budżet',
                'verbose_name_plural': 'Budżety',
                'db_table': 'budzet',
                'managed': True,
            },
        ),
    ]
